// Vercel Serverless Function for months data
const DEFAULT_MONTHS = [
    "january", "february", "march", "april", "may", "june",
    "july", "august", "september", "october", "november", "december"
];

const DEFAULT_DATA = {
    january: {
        name: "January",
        math: "Srinivasa Ramanujan 🇮🇳",
        quote: "An equation for me has no meaning, unless it expresses a thought of God.",
        bg: "linear-gradient(135deg, #4834d4, #686de0)",
        offset: 3, days: 31,
        facts: [
            {t: "The multiplicative identity.", q: "What happens when you multiply any number by 1?", a: "stays the same"},
            {t: "The only even prime Number.", q: "Can you think of another even prime number? Why or why not?", a: "no"},
            {t: "The smallest odd prime number.", q: "What are the first three triangular numbers?", a: "1, 3, 6"},
            {t: "The smallest composite Number.", q: "Why is 4 a composite number?", a: "2x2"},
            {t: "A Pentagonal Number.", q: "How many sides does a pentagon have?", a: "5"},
            {t: "The smallest perfect Number.", q: "The next perfect number is 28. Can you find its divisors to check?", a: "1, 2, 4, 7, 14"},
            {t: "A lucky prime number.", q: "Can you name a shape with 7 sides?", a: "heptagon"},
            {t: "The first perfect cube (2³)", q: "What is the next perfect cube after 8?", a: "27"},
            {t: "The first odd composite number.", q: "What two numbers can you multiply to get 9?", a: "3x3"},
            {t: "Base of our decimal number system.", q: "How many 10s are in 100?", a: "10"},
            {t: "A Palindromic Prime Number.", q: "What is the next palindromic number after 11?", a: "22"},
            {t: "A dozen. It has the most divisors!", q: "How many items are in two dozen?", a: "24"},
            {t: "A Fibonacci Number.", q: "What are the two Fibonacci numbers that come before 13?", a: "5, 8"},
            {t: "Atomic number of Silicon.", q: "What electronic devices use silicon chips?", a: "computers"},
            {t: "The magic sum in a 3x3 magic square.", q: "Can you arrange numbers 1-9 in a 3x3 grid so each row, column, and diagonal sums to 15?", a: "yes"},
            {t: "A perfect square (4²).", q: "What is 16 divided by 2?", a: "8"},
            {t: "A Fermat Prime.", q: "What two prime numbers add up to 17?", a: "2, 15"},
            {t: "Twice the sum of its digits (1+8=9, 9x2=18).", q: "What is half of 18?", a: "9"},
            {t: "A Happy Number!", q: "Can you check if 7 is a happy number?", a: "yes"},
            {t: "The number of faces on an icosahedron.", q: "How many fingers and toes do you have in total?", a: "20"},
            {t: "A Triangular Number.", q: "What is the next triangular number after 21?", a: "28"},
            {t: "A palindromic number.", q: "If a circle's diameter is 7, its circumference is approximately 22. What is the name for this ratio (22/7)?", a: "pi"},
            {t: "Pairs of chromosomes in a human.", q: "Which prime number comes right before 23?", a: "19"},
            {t: "4! (4 factorial) = 24.", q: "How many hours are in a day?", a: "24"},
            {t: "A perfect square (5²).", q: "How many cents are in a quarter?", a: "25"},
            {t: "Letters in the English alphabet.", q: "Can you say the alphabet backwards?", a: "yes"},
            {t: "A perfect cube (3³).", q: "If a big cube is made of 3x3x3 smaller cubes, how many small cubes are there in total?", a: "27"},
            {t: "The second perfect number.", q: "Is 28 a triangular number?", a: "yes"},
            {t: "A prime number.", q: "How many days are in February in a leap year?", a: "29"},
            {t: "Days in Apr, Jun, Sep, Nov.", q: "What is 3 x 10?", a: "30"},
            {t: "A Mersenne prime (2⁵-1).", q: "How many days are in January?", a: "31"}
        ]
    },
    february: {
        name: "February",
        math: "C. R. Rao 🇮🇳",
        quote: "The only way to learn mathematics is to do mathematics.",
        bg: "linear-gradient(135deg, #6c5ce7, #a29bfe)",
        offset: 6, days: 28,
        facts: [
            {t: "1", q: "How can you make 1 using only the number 1?", a: "1"},
            {t: "2", q: "How can you make 2 using only the number 2?", a: "2"},
            {t: "1 + 2", q: "Can you find another way to make 3 using 1s and 2s?", a: "1+1+1"},
            {t: "2 × 2", q: "How can you make 4 using only addition of 1s and 2s?", a: "2+2"},
            {t: "(2 × 2) + 1", q: "Can you make 5 using three 2s and one 1?", a: "2+2+2-1"},
            {t: "(2 × 2) + 2", q: "What is 3 times 2?", a: "6"},
            {t: "(2 × 2) + 2 + 1", q: "How would you write 7 using three 2s and one 1?", a: "2+2+2+1"},
            {t: "2 × 2 × 2", q: "How many 2s do you add together to get 8?", a: "4"},
            {t: "(2 × 2 × 2) + 1", q: "Can you make 9 using the number 3 twice?", a: "3x3"},
            {t: "(2 × 2 × 2) + 2", q: "What is 5 times 2?", a: "10"},
            {t: "2×2×2 + 2 + 1", q: "Is 11 a prime number?", a: "yes"},
            {t: "2×2 + 2+2+2+2", q: "How many eggs in a dozen?", a: "12"},
            {t: "2×2×2 + 2+2+1", q: "Is 13 considered a lucky or unlucky number?", a: "unlucky"},
            {t: "2×(2+2+2+1)", q: "How many days are in two weeks?", a: "14"},
            {t: "(2+1)×(2+2+1)", q: "What is 3 times 5?", a: "15"},
            {t: "2 × 2 × 2 × 2", q: "What is 4 times 4?", a: "16"},
            {t: "2×2×2×2 + 1", q: "Is 17 a prime number?", a: "yes"},
            {t: "2×(2×2+2+2+1)", q: "What is 9 times 2?", a: "18"},
            {t: "2×2×(2+2)+2+1", q: "Which prime number comes after 19?", a: "23"},
            {t: "(2+2)×(2+2+1)", q: "What is 4 times 5?", a: "20"},
            {t: "(2+1)×(2+2+2+1)", q: "What is 3 times 7?", a: "21"},
            {t: "2 × (2×2+2×2-2+1)", q: "What is 11 times 2?", a: "22"},
            {t: "2×(2×2+2×2-1)-1", q: "Is 23 a prime number?", a: "yes"},
            {t: "2 × 2 × 2 × (2 + 1)", q: "What is 4 times 6?", a: "24"},
            {t: "(2+2+1) × (2+2+1)", q: "What is 5 times 5?", a: "25"},
            {t: "2 × (2×2×2 + 2 + 2 + 1)", q: "How many letters are in the alphabet?", a: "26"},
            {t: "(2+1) × (2+1) × (2+1)", q: "What is 3 times 3 times 3?", a: "27"},
            {t: "(2+2) × (2+2+2+1)", q: "What is 4 times 7?", a: "28"}
        ]
    },
    march: {
        name: "March",
        math: "Shakuntala Devi 🇮🇳",
        quote: "Without mathematics, there's nothing you can do. Everything around you is numbers.",
        bg: "linear-gradient(135deg, #00b894, #55efc4)",
        offset: 6, days: 31,
        facts: [
            {t: "Mono (or Uni)", q: "What does the 'uni' in 'unicycle' mean?", a: "one"},
            {t: "Di or Bi", q: "A bicycle has two wheels. What does the 'bi' mean?", a: "two"},
            {t: "Tri", q: "How many sides does a triangle have?", a: "3"},
            {t: "Tetra or Quadri", q: "A 'quad' has four wheels. What shape has four sides?", a: "square"},
            {t: "Penta", q: "The Pentagon building in the US has five sides. What does 'penta' mean?", a: "five"},
            {t: "Hexa", q: "A honeycomb is made of hexagons. How many sides do they have?", a: "6"},
            {t: "Hepta", q: "A heptathlon is an athletic contest with seven events. What does 'hepta' mean?", a: "seven"},
            {t: "Octa", q: "How many legs does an octopus have?", a: "8"},
            {t: "Nona", q: "A nonagon is a shape with nine sides. Can you draw one?", a: "yes"},
            {t: "Deca", q: "How many years are in a decade?", a: "10"},
            {t: "Undeca", q: "An 'undecagon' is a shape with how many sides?", a: "11"},
            {t: "Dodeca", q: "A dodecahedron is a 3D shape with 12 faces. What famous game uses this shape as a die?", a: "d&d"},
            {t: "Trideca", q: "What does 'trideca' mean in 'tridecaphobia' (fear of the number 13)?", a: "thirteen"},
            {t: "Tetradeca", q: "If 'tetra' is 4 and 'deca' is 10, what number is tetradeca?", a: "14"},
            {t: "Pentadeca", q: "If 'penta' is 5 and 'deca' is 10, what number is pentadeca?", a: "15"},
            {t: "Hexadeca", q: "What is 10 + 6?", a: "16"},
            {t: "Heptadeca", q: "What is 10 + 7?", a: "17"},
            {t: "Octadeca", q: "What is 10 + 8?", a: "18"},
            {t: "Enneadeca", q: "What is 10 + 9?", a: "19"},
            {t: "Icosa", q: "An icosahedron has 20 faces. What does 'icosa' mean?", a: "twenty"},
            {t: "Icosikaihena (20 + 1)", q: "What is another name for the number 21?", a: "twenty-one"},
            {t: "Icosikaidi", q: "What is 20 + 2?", a: "22"},
            {t: "Icosikaitri", q: "What is 20 + 3?", a: "23"},
            {t: "Icosikaittra", q: "What is 20 + 4?", a: "24"},
            {t: "Icosikaipenta", q: "What is 20 + 5?", a: "25"},
            {t: "Icosikaihexa", q: "What is 20 + 6?", a: "26"},
            {t: "Icosikaihepta", q: "What is 20 + 7?", a: "27"},
            {t: "Icosikaiocta", q: "What is 20 + 8?", a: "28"},
            {t: "Icosikaiennea", q: "What is 20 + 9?", a: "29"},
            {t: "Triaconta", q: "If 'tri' is 3 and 'deca' is 10, what number is 'triaconta'?", a: "30"},
            {t: "Triacontakaihena (30 + 1)", q: "How many days are in March?", a: "31"}
        ]
    },
    april: {
        name: "April",
        math: "D. R. Kaprekar 🇮🇳",
        quote: "A different taste of numbers.",
        bg: "linear-gradient(135deg, #e17055, #fab1a0)",
        offset: 2, days: 30,
        facts: [
            {t: "+ (Addition)", q: "What is 5 + 5?", a: "10"},
            {t: "- (Subtraction)", q: "What is 10 - 3?", a: "7"},
            {t: "× (Multiplication)", q: "What is 4 × 3?", a: "12"},
            {t: "÷ (Division)", q: "What is 12 ÷ 4?", a: "3"},
            {t: "= (Equality)", q: "Is 2 + 3 = 5? (True or False)", a: "true"},
            {t: "≠ (Not Equal)", q: "Is 4 ≠ 4? (True or False)", a: "false"},
            {t: "< (Less Than)", q: "Which is true: 7 < 5 or 5 < 7?", a: "5 < 7"},
            {t: "> (Greater Than)", q: "Which is true: 8 > 10 or 10 > 8?", a: "10 > 8"},
            {t: "≤ (Less Than or Equal To)", q: "Is 9 ≤ 9? (True or False)", a: "true"},
            {t: "≥ (Greater Than or Equal To)", q: "Is 10 ≥ 11? (True or False)", a: "false"},
            {t: "√ (Square Root)", q: "What is the square root of 9 (√9)?", a: "3"},
            {t: "π (Pi)", q: "Pi is famously irrational. What are its first three digits?", a: "3.14"},
            {t: "% (Percent)", q: "What is 50% of 20?", a: "10"},
            {t: "∞ (Infinity)", q: "Can you count to infinity? Why or why not?", a: "no"},
            {t: "∑ (Sigma, Summation)", q: "What is the sum of the first three numbers (1+2+3)?", a: "6"},
            {t: "∠ (Angle)", q: "What do you call an angle that is exactly 90 degrees?", a: "right angle"},
            {t: "≡ (Identically Equal)", q: "Is a triangle with sides 3,4,5 identical to one with sides 3,4,5?", a: "yes"},
            {t: "Δ (Delta)", q: "In science, Delta often means 'change'. If temperature changes from 10 to 15, what is the delta?", a: "5"},
            {t: "∩ (Intersection)", q: "If Set A is {1,2,3} and Set B is {3,4,5}, what is their intersection?", a: "3"},
            {t: "∪ (Union)", q: "If Set A is {1,2} and Set B is {3,4}, what is their union?", a: "1,2,3,4"},
            {t: "⊂ (Subset)", q: "Is {a, b} a subset of {a, b, c}?", a: "yes"},
            {t: "⊄ (Not a Subset)", q: "Is {a, d} a subset of {a, b, c}?", a: "no"},
            {t: "∝ (Proportional To)", q: "If the number of cookies you buy is proportional to the cost, what happens to the cost if you buy more cookies?", a: "increases"},
            {t: "∫ (Integral)", q: "The integral helps find the area under a curve. What shape's area is found by length × width?", a: "rectangle"},
            {t: "∈ (Element of)", q: "Is 'cat' an element of the set of {animals}?", a: "yes"},
            {t: "∉ (Not an Element of)", q: "Is 'car' an element of the set of {animals}?", a: "no"},
            {t: "! (Factorial)", q: "What is 3! (3 × 2 × 1)?", a: "6"},
            {t: "∽ (Similar)", q: "Are all squares similar to each other, even if they are different sizes?", a: "yes"},
            {t: "‖ (Parallel)", q: "Can you name something in your room that has parallel lines?", a: "door"},
            {t: "≈ (Approximately Equal)", q: "Pi (π) is approximately equal to what fraction?", a: "22/7"}
        ]
    },
    may: {
        name: "May",
        math: "Aryabhata",
        quote: "Earth rotates about its axis.",
        bg: "#0984e3",
        offset: 4,
        days: 31,
        theme: "Astronomy & Zero"
    },
    june: {
        name: "June",
        math: "Bhaskara II",
        quote: "Infinity is that which remains after subtraction.",
        bg: "#d63031",
        offset: 0,
        days: 30,
        theme: "Calculus & Flowers"
    },
    july: {
        name: "July",
        math: "Brahmagupta",
        quote: "Zero is the sum of a number and its negative.",
        bg: "#e84393",
        offset: 2,
        days: 31,
        theme: "Negatives"
    },
    august: {
        name: "August",
        math: "Satyendra Nath Bose",
        quote: "Bosons are named after him!",
        bg: "#636e72",
        offset: 5,
        days: 31,
        theme: "Quantum Statistics"
    },
    september: {
        name: "September",
        math: "P.C. Mahalanobis",
        quote: "Statistics is key to planning.",
        bg: "#fdcb6e",
        offset: 1,
        days: 30,
        theme: "Data Science"
    },
    october: {
        name: "October",
        math: "Harish-Chandra",
        quote: "Mathematics is art.",
        bg: "#a29bfe",
        offset: 3,
        days: 31,
        theme: "Representation Theory"
    },
    november: {
        name: "November",
        math: "Manjul Bhargava",
        quote: "Math is like music.",
        bg: "#00cec9",
        offset: 6,
        days: 30,
        theme: "Number Theory"
    },
    december: {
        name: "December",
        math: "Madhava",
        quote: "Infinite series for Pi.",
        bg: "#2d3436",
        offset: 1,
        days: 31,
        theme: "Infinite Series"
    }
};

module.exports = function handler(req, res) {
    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.status(200).json({ months: DEFAULT_MONTHS, data: DEFAULT_DATA });
};
