// Vercel Serverless Function for months data
const DEFAULT_MONTHS = [
    "january", "february", "march", "april", "may", "june",
    "july", "august", "september", "october", "november", "december"
];

const DEFAULT_DATA = {
    january: {
        name: "January",
        math: "Srinivasa Ramanujan 🇮🇳",
        quote: "An equation for me has no meaning, unless it expresses a thought of God.",
        bg: "linear-gradient(135deg, #4834d4, #686de0)",
        offset: 3, days: 31,
        facts: [
            {t: "The multiplicative identity.", q: "What happens when you multiply any number by 1?", a: "stays the same"},
            {t: "The only even prime Number.", q: "Can you think of another even prime number?", a: "no"},
            {t: "The smallest odd prime number.", q: "What are the first three triangular numbers?", a: "1, 3, 6"},
            {t: "The smallest composite Number.", q: "Why is 4 a composite number?", a: "2x2"},
            {t: "A Pentagonal Number.", q: "How many sides does a pentagon have?", a: "5"},
            {t: "The smallest perfect Number.", q: "What are the divisors of 28?", a: "1, 2, 4, 7, 14"},
            {t: "A lucky prime number.", q: "What shape has 7 sides?", a: "heptagon"},
            {t: "The first perfect cube (2³)", q: "What is the next perfect cube after 8?", a: "27"},
            {t: "The first odd composite number.", q: "What two numbers multiply to get 9?", a: "3x3"},
            {t: "Base of our decimal system.", q: "How many 10s are in 100?", a: "10"},
            {t: "A Palindromic Prime.", q: "What palindromic number comes after 11?", a: "22"},
            {t: "A dozen!", q: "How many items in two dozen?", a: "24"},
            {t: "A Fibonacci Number.", q: "What Fibonacci numbers come before 13?", a: "5, 8"},
            {t: "Atomic number of Silicon.", q: "What devices use silicon chips?", a: "computers"},
            {t: "Magic sum in a 3x3 square.", q: "Each row/column/diagonal sums to?", a: "15"},
            {t: "A perfect square (4²).", q: "What is 16 divided by 2?", a: "8"},
            {t: "A Fermat Prime.", q: "What two primes add to 17?", a: "2 and 15"},
            {t: "Twice its digit sum.", q: "What is half of 18?", a: "9"},
            {t: "A Happy Number!", q: "Is 7 a happy number?", a: "yes"},
            {t: "Faces on an icosahedron.", q: "How many fingers and toes total?", a: "20"},
            {t: "A Triangular Number.", q: "Next triangular after 21?", a: "28"},
            {t: "A palindromic number.", q: "What is 22/7 approximately?", a: "pi"},
            {t: "Human chromosome pairs.", q: "Prime number before 23?", a: "19"},
            {t: "4! (4 factorial).", q: "Hours in a day?", a: "24"},
            {t: "A perfect square (5²).", q: "Cents in a quarter?", a: "25"},
            {t: "Letters in alphabet.", q: "How many letters A-Z?", a: "26"},
            {t: "A perfect cube (3³).", q: "3×3×3 = ?", a: "27"},
            {t: "Second perfect number.", q: "Is 28 triangular?", a: "yes"},
            {t: "A prime number.", q: "Days in leap February?", a: "29"},
            {t: "Days in Apr, Jun, Sep, Nov.", q: "What is 3 × 10?", a: "30"},
            {t: "A Mersenne prime (2⁵-1).", q: "Days in January?", a: "31"}
        ]
    },
    february: {
        name: "February",
        math: "C. R. Rao 🇮🇳",
        quote: "The only way to learn mathematics is to do mathematics.",
        bg: "linear-gradient(135deg, #6c5ce7, #a29bfe)",
        offset: 6, days: 28,
        facts: [
            {t: "1", q: "1 using only 1?", a: "1"},
            {t: "2", q: "2 using only 2?", a: "2"},
            {t: "1 + 2", q: "Another way to make 3?", a: "1+1+1"},
            {t: "2 × 2", q: "2+2 = ?", a: "4"},
            {t: "(2 × 2) + 1", q: "2+2+1 = ?", a: "5"},
            {t: "(2 × 2) + 2", q: "3 times 2?", a: "6"},
            {t: "(2×2)+2+1", q: "2+2+2+1 = ?", a: "7"},
            {t: "2 × 2 × 2", q: "How many 2s add to 8?", a: "4"},
            {t: "(2×2×2)+1", q: "3×3 = ?", a: "9"},
            {t: "(2×2×2)+2", q: "5 times 2?", a: "10"},
            {t: "2×2×2+2+1", q: "Is 11 prime?", a: "yes"},
            {t: "2×2+2+2+2+2", q: "Eggs in a dozen?", a: "12"},
            {t: "2×2×2+2+2+1", q: "Is 13 lucky or unlucky?", a: "unlucky"},
            {t: "2×(2+2+2+1)", q: "Days in two weeks?", a: "14"},
            {t: "(2+1)×(2+2+1)", q: "3 times 5?", a: "15"},
            {t: "2×2×2×2", q: "4 times 4?", a: "16"},
            {t: "2×2×2×2+1", q: "Is 17 prime?", a: "yes"},
            {t: "2×(2×2+2+2+1)", q: "9 times 2?", a: "18"},
            {t: "2×2×(2+2)+2+1", q: "Next prime after 19?", a: "23"},
            {t: "(2+2)×(2+2+1)", q: "4 times 5?", a: "20"},
            {t: "(2+1)×(2+2+2+1)", q: "3 times 7?", a: "21"},
            {t: "2×(2×2+2×2-2+1)", q: "11 times 2?", a: "22"},
            {t: "2×(2×2+2×2-1)-1", q: "Is 23 prime?", a: "yes"},
            {t: "2×2×2×(2+1)", q: "4 times 6?", a: "24"},
            {t: "(2+2+1)×(2+2+1)", q: "5 times 5?", a: "25"},
            {t: "2×(2×2×2+2+2+1)", q: "Letters in alphabet?", a: "26"},
            {t: "(2+1)×(2+1)×(2+1)", q: "3×3×3 = ?", a: "27"},
            {t: "(2+2)×(2+2+2+1)", q: "4 times 7?", a: "28"}
        ]
    },
    march: {
        name: "March",
        math: "Shakuntala Devi 🇮🇳",
        quote: "Without mathematics, there's nothing you can do.",
        bg: "linear-gradient(135deg, #00b894, #55efc4)",
        offset: 6, days: 31,
        facts: [
            {t: "Mono (Uni)", q: "'Uni' in unicycle means?", a: "one"},
            {t: "Di or Bi", q: "'Bi' in bicycle means?", a: "two"},
            {t: "Tri", q: "Sides of a triangle?", a: "3"},
            {t: "Tetra or Quadri", q: "Shape with 4 sides?", a: "square"},
            {t: "Penta", q: "'Penta' means?", a: "five"},
            {t: "Hexa", q: "Sides of a hexagon?", a: "6"},
            {t: "Hepta", q: "'Hepta' means?", a: "seven"},
            {t: "Octa", q: "Octopus legs?", a: "8"},
            {t: "Nona", q: "Nonagon sides?", a: "9"},
            {t: "Deca", q: "Years in a decade?", a: "10"},
            {t: "Undeca", q: "Undecagon sides?", a: "11"},
            {t: "Dodeca", q: "Dodecahedron faces?", a: "12"},
            {t: "Trideca", q: "'Trideca' means?", a: "thirteen"},
            {t: "Tetradeca", q: "4 + 10 = ?", a: "14"},
            {t: "Pentadeca", q: "5 + 10 = ?", a: "15"},
            {t: "Hexadeca", q: "6 + 10 = ?", a: "16"},
            {t: "Heptadeca", q: "7 + 10 = ?", a: "17"},
            {t: "Octadeca", q: "8 + 10 = ?", a: "18"},
            {t: "Enneadeca", q: "9 + 10 = ?", a: "19"},
            {t: "Icosa", q: "'Icosa' means?", a: "twenty"},
            {t: "Icosikaihena", q: "20 + 1 = ?", a: "21"},
            {t: "Icosikaidi", q: "20 + 2 = ?", a: "22"},
            {t: "Icosikaitri", q: "20 + 3 = ?", a: "23"},
            {t: "Icosikaittra", q: "20 + 4 = ?", a: "24"},
            {t: "Icosikaipenta", q: "20 + 5 = ?", a: "25"},
            {t: "Icosikaihexa", q: "20 + 6 = ?", a: "26"},
            {t: "Icosikaihepta", q: "20 + 7 = ?", a: "27"},
            {t: "Icosikaiocta", q: "20 + 8 = ?", a: "28"},
            {t: "Icosikaiennea", q: "20 + 9 = ?", a: "29"},
            {t: "Triaconta", q: "'Triaconta' means?", a: "30"},
            {t: "Triacontakaihena", q: "Days in March?", a: "31"}
        ]
    },
    april: {
        name: "April",
        math: "D. R. Kaprekar 🇮🇳",
        quote: "A different taste of numbers.",
        bg: "linear-gradient(135deg, #e17055, #fab1a0)",
        offset: 2, days: 30,
        facts: [
            {t: "+ Addition", q: "5 + 5 = ?", a: "10"},
            {t: "- Subtraction", q: "10 - 3 = ?", a: "7"},
            {t: "× Multiplication", q: "4 × 3 = ?", a: "12"},
            {t: "÷ Division", q: "12 ÷ 4 = ?", a: "3"},
            {t: "= Equality", q: "Is 2+3=5?", a: "true"},
            {t: "≠ Not Equal", q: "Is 4≠4?", a: "false"},
            {t: "< Less Than", q: "5 < 7?", a: "true"},
            {t: "> Greater Than", q: "10 > 8?", a: "true"},
            {t: "≤ Less or Equal", q: "Is 9≤9?", a: "true"},
            {t: "≥ Greater or Equal", q: "Is 10≥11?", a: "false"},
            {t: "√ Square Root", q: "√9 = ?", a: "3"},
            {t: "π Pi", q: "First digits of Pi?", a: "3.14"},
            {t: "% Percent", q: "50% of 20?", a: "10"},
            {t: "∞ Infinity", q: "Can you count to infinity?", a: "no"},
            {t: "∑ Summation", q: "1+2+3 = ?", a: "6"},
            {t: "∠ Angle", q: "90° angle is called?", a: "right angle"},
            {t: "≡ Identical", q: "Are congruent triangles identical?", a: "yes"},
            {t: "Δ Delta", q: "Change from 10 to 15?", a: "5"},
            {t: "∩ Intersection", q: "{1,2,3}∩{3,4,5} = ?", a: "3"},
            {t: "∪ Union", q: "{1,2}∪{3,4} = ?", a: "1,2,3,4"},
            {t: "⊂ Subset", q: "Is {a,b}⊂{a,b,c}?", a: "yes"},
            {t: "⊄ Not Subset", q: "Is {a,d}⊂{a,b,c}?", a: "no"},
            {t: "∝ Proportional", q: "More cookies = more cost?", a: "yes"},
            {t: "∫ Integral", q: "Area of rectangle formula?", a: "length times width"},
            {t: "∈ Element of", q: "Is cat∈{animals}?", a: "yes"},
            {t: "∉ Not Element", q: "Is car∈{animals}?", a: "no"},
            {t: "! Factorial", q: "3! = ?", a: "6"},
            {t: "∽ Similar", q: "Are all squares similar?", a: "yes"},
            {t: "‖ Parallel", q: "Do railroad tracks have parallel lines?", a: "yes"},
            {t: "≈ Approximately", q: "Pi ≈ 22/?", a: "7"}
        ]
    },
    may: { name: "May", math: "Aryabhata", quote: "Earth rotates.", bg: "#0984e3", offset: 4, days: 31, theme: "Astronomy" },
    june: { name: "June", math: "Bhaskara II", quote: "Infinity remains.", bg: "#d63031", offset: 0, days: 30, theme: "Calculus" },
    july: { name: "July", math: "Brahmagupta", quote: "Zero is sum.", bg: "#e84393", offset: 2, days: 31, theme: "Negatives" },
    august: { name: "August", math: "S.N. Bose", quote: "Bosons!", bg: "#636e72", offset: 5, days: 31, theme: "Quantum" },
    september: { name: "September", math: "P.C. Mahalanobis", quote: "Statistics.", bg: "#fdcb6e", offset: 1, days: 30, theme: "Data" },
    october: { name: "October", math: "Harish-Chandra", quote: "Math is art.", bg: "#a29bfe", offset: 3, days: 31, theme: "Theory" },
    november: { name: "November", math: "Manjul Bhargava", quote: "Math is music.", bg: "#00cec9", offset: 6, days: 30, theme: "Numbers" },
    december: { name: "December", math: "Madhava", quote: "Infinite series.", bg: "#2d3436", offset: 1, days: 31, theme: "Series" }
};

module.exports = function handler(req, res) {
    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.status(200).json({ months: DEFAULT_MONTHS, data: DEFAULT_DATA });
};
